name: .NET CI

on:
  push:
    branches: [ "homework3" ]
  pull_request:
    branches: [ "homework3" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore MyWcProject/MyWc.sln
      
    - name: Build
      run: dotnet build MyWcProject/MyWc.sln --no-restore
      
    - name: Test
      run: dotnet test MyWcProject/MyWc.sln --no-build --verbosity normal
