name: Lab 2 CI Pipeline

on:
  push:
    branches: [ "lab2-docker" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean and lowercase image name
        run: |
          CLEAN_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
          echo "IMAGE_NAME_LOWER=$CLEAN_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:latest

  test:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean and lowercase image name
        run: |
          CLEAN_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
          echo "IMAGE_NAME_LOWER=$CLEAN_NAME" >> $GITHUB_ENV

      - name: Pull Docker image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:latest

      - name: Run tests inside container
        run: docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:latest pytest test_app.py
